import type { Metadata } from "next";
import "./globals.css";

import PlausibleProvider from "next-plausible";
import { Inter } from "next/font/google";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          defer
          data-domain="build-recomendation.vercel.app"
          src="https://plausible.io/js/script.js"
        ></Script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
